module.exports = (sequelize, DataTypes) => {
    const Course = sequelize.define('course', {
        id: {
            DataType: Integer,
            primaryKey: true,
            autoGenerated: true
        },
        userId: {
            DataType: String
        },
        title: {
            DataType: String
        },
        description: {
            DataType: Text
        },
        estimatedTime: {
            DataType: String,
            allowNull:true
        },
        materialsNeeded: {
            DataType: String,
            allowNull: true
        }
    })
    user.associate = models => {
        user.belongsTo(models.Customer)
    }
    return Course
}