module.exports = (sequelize, DataTypes) => {
    const user = sequelize.define('user', {
        id: {
            DataType: Integer,
            primaryKey: true,
            autoGenerated: true
        },
        firstName: {
            DataType: String
        },
        lastName: {
            DataType: String
        },
        emailAddress: {
            DataType: String
        },
        password: {
            DataType: String
        }
    })
    user.associate = models => {
        user.belongsTo(models.Customer)
    }
    return user
}